USE db_biblioteca;

INSERT INTO tb_editora (nm_editora, ds_editora) VALUES
('Rocco', 'Líder em publicações literárias, oferece uma vasta gama de obras de renomados autores nacionais e internacionais.'),
('Companhia das Letras', 'Uma das editoras mais renomadas do Brasil, com um catálogo diversificado de autores brasileiros e estrangeiros.'),
('Intrínseca', 'Especializada em best-sellers e livros de ficção, é conhecida por lançar grandes sucessos literários.'),
('Globo Livros', 'Parte do Grupo Globo, publica uma ampla variedade de gêneros, incluindo ficção, não-ficção e livros de referência.'),
('Editora Record', 'Uma das editoras mais antigas e respeitadas do país, com um histórico de publicações premiadas.'),
('Objetiva', 'Focada em literatura de qualidade, tem em seu catálogo autores de renome e obras premiadas.'),
('Leya', 'Uma editora que oferece uma ampla gama de gêneros, incluindo literatura, não-ficção, e-books e educação.'),
('Saraiva', 'Conhecida principalmente por suas publicações educacionais, a Saraiva também oferece uma variedade de títulos de entretenimento.'),
('Novo Século', 'Especializada em literatura brasileira e estrangeira, com uma abordagem para autores estreantes.'),
('Editora Sextante', 'Famosa por seus livros de desenvolvimento pessoal e autoajuda, além de romances e best-sellers.'),
('DarkSide Books', 'Editora focada em livros de terror e suspense, com edições caprichadas e ilustrações impressionantes.'),
('Gutenberg', 'Especializada em literatura infantojuvenil, oferece uma ampla variedade de livros para jovens leitores.'),
('Cia das Letras', 'Uma das maiores editoras do Brasil, com um catálogo diversificado que inclui obras literárias e de não-ficção.'),
('Martins Fontes', 'Editora com tradição em publicações acadêmicas e obras de referência.'),
('Editora 34', 'Conhecida por suas edições de qualidade de obras literárias e de ensaios críticos.')
('José Olympio', 'A Editora José Olympio, fundada em 1931, é um pilar da cultura brasileira, publicando obras literárias de destaque, incluindo clássicos mundiais como "O Sol é Para Todos" e "O Menino do Dedo Verde".');



INSERT INTO tb_livro (nm_livro, ds_livro, cd_editora, isbn10, isbn13) VALUES
('Jogos Vorazes', 'Num futuro distópico, Katniss Everdeen luta pela sobrevivência ao participar dos brutais Jogos Vorazes, um evento mortal criado pelo governo. Enquanto enfrenta adversários, ela desafia o sistema e se torna um símbolo de resistência.', 1, '655532144X', '9786555321449'),
('O Sol é para todo', 'Clássico da literatura americana, "O Sol é Para Todos" de Harper Lee é um livro sobre racismo e injustiça. A história se passa nos anos 1930, quando um advogado defende um homem negro acusado de estuprar uma mulher branca. O livro é narrado pela filha do advogado, Scout, e aborda temas como tolerância, perda da inocência e conceito de justiça.', 16, '8503009498', '9788503009492'),
('Harry Potter e a Pedra Filosofal', '"Harry Potter e a Pedra Filosofal" é o início da jornada de um jovem bruxo, Harry, que descobre seu destino ao entrar em Hogwarts e enfrentar o mistério da pedra que concede imortalidade.', 1, '8532511015', '9788532511010'),
('Orgulho e Preconceito', 'Um romance clássico de Jane Austen que explora temas de amor, casamento e preconceito na sociedade inglesa do século XIX.'),
('O Diário de Anne Frank', 'O comovente diário escrito por Anne Frank enquanto ela e sua família estavam escondidos dos nazistas durante a Segunda Guerra Mundial.'),
('A Revolução dos Bichos', 'Uma sátira política escrita por George Orwell, que utiliza animais de uma fazenda como alegorias para comentar sobre a corrupção do poder.'),
('O Pequeno Príncipe', 'Uma história atemporal de Antoine de Saint-Exupéry sobre a amizade e a busca pelo significado da vida.'),
('1984', 'Um romance distópico de George Orwell que descreve um regime totalitário controlado pelo "Grande Irmão" e a luta de um homem contra a opressão.'),
('O Grande Gatsby', 'Um clássico de F. Scott Fitzgerald que explora a decadência da alta sociedade americana na década de 1920.'),
('O Apanhador no Campo de Centeio', 'Uma obra de J.D. Salinger que narra a jornada emocional de um adolescente, Holden Caulfield.'),
('Senhor dos Anéis', 'Uma épica saga de fantasia escrita por J.R.R. Tolkien que segue a busca pelo Um Anel e a luta contra o Senhor Sombrio, Sauron.'),
('A Menina que Roubava Livros', 'Um romance de Markus Zusak ambientado na Alemanha nazista, narrado pela Morte e centrado na vida de Liesel Meminger.'),
('Jane Eyre', 'Um romance clássico de Charlotte Brontë que segue a vida de Jane Eyre, uma jovem órfã em busca de amor e independência.'),
('As Crônicas de Nárnia', 'Uma série de livros de C.S. Lewis que transporta leitores para um mundo mágico repleto de aventuras e metáforas religiosas.'),
('Senhor das Moscas', 'Um romance de William Golding que explora a natureza humana por meio do comportamento de crianças isoladas em uma ilha deserta.'),
('Romeu e Julieta', 'Uma tragédia de William Shakespeare que conta a história de amor proibido entre dois jovens de famílias rivais em Verona.'),
('Harry Potter e a Câmara Secreta', 'No segundo livro da série, Harry Potter retorna a Hogwarts para enfrentar mistérios e perigos escondidos na escola de magia e bruxaria.'),
('Harry Potter e o Prisioneiro de Azkaban', 'O terceiro livro da série acompanha Harry Potter enquanto ele descobre segredos sobre seu passado e enfrenta ameaças de um prisioneiro foragido.'),
('Harry Potter e o Cálice de Fogo', 'Neste quarto livro, Harry Potter participa do Torneio Tribruxo e enfrenta desafios mortais enquanto descobre um novo mistério.'),
('Harry Potter e a Ordem da Fênix', 'O quinto livro narra o treinamento de Harry e seus amigos para enfrentar o retorno de Lord Voldemort e a formação da Ordem da Fênix.'),
('Harry Potter e o Enigma do Príncipe', 'No sexto livro, Harry Potter desvenda segredos sobre o passado de Voldemort e enfrenta a crescente ameaça do Lorde das Trevas.'),
('Harry Potter e as Relíquias da Morte', 'O último livro da série segue Harry Potter em sua missão final para destruir as Horcruxes de Voldemort e enfrentar o confronto final.'),
('A Menina e o Porquinho', 'Uma história encantadora de E. B. White sobre a amizade entre uma menina chamada Fern e um porco chamado Wilbur.'),
('Mulherzinhas', 'Um clássico de Louisa May Alcott que narra as vidas das irmãs March enquanto crescem e enfrentam desafios durante a Guerra Civil Americana.'),
('Jogos Vorazes: Em Chamas', 'A continuação de "Jogos Vorazes" acompanha Katniss e Peeta em sua participação nos Jogos Vorazes da Edição Quell.'),
('Jogos Vorazes: A Esperança', 'O terceiro livro da trilogia "Jogos Vorazes" segue Katniss enquanto ela lidera uma revolta contra o Capitólio.'),
('A Cantiga dos Pássaros e Serpentes', 'Um livro de Suzanne Collins que explora a juventude de Coriolanus Snow, o futuro presidente do Capitólio.'),
('O Hobbit', 'Uma aventura épica de J.R.R. Tolkien que segue Bilbo Bolseiro em sua jornada para recuperar o tesouro guardado por Smaug, o dragão.'),
('Ratos e Homens', 'Um clássico de John Steinbeck que conta a história de dois trabalhadores migrantes, George e Lennie, durante a Grande Depressão.'),
('Fahrenheit 451', 'Um livro distópico de Ray Bradbury que descreve uma sociedade onde os livros são proibidos e queimados por bombeiros governamentais.'),
('Alice no País das Maravilhas e Através do Espelho', 'As aventuras surreais de Alice em dois mundos fantásticos, escritas por Lewis Carroll.'),
('O Morro dos Ventos Uivantes', 'Um romance gótico de Emily Brontë que narra uma história de paixão e vingança na sombria paisagem de Yorkshire.'),
('O Retrato de Dorian Gray', 'A obra-prima de Oscar Wilde sobre um homem cujo retrato envelhece enquanto ele permanece jovem e imoral.'),
('E o Vento Levou', 'Um romance épico de Margaret Mitchell ambientado durante a Guerra Civil Americana e a Reconstrução.'),
('A Bíblia Sagrada', 'O texto religioso central do Cristianismo, composto por livros do Antigo e do Novo Testamento.'),
('O Guia do Mochileiro das Galáxias', 'O primeiro livro da série de comédia de ficção científica escrita por Douglas Adams, que segue as aventuras de Arthur Dent pelo universo.'),
('Hamlet', 'A tragédia clássica de William Shakespeare que explora temas de vingança, loucura e poder.'),
('Os Miseráveis', 'O épico romântico de Victor Hugo que segue a vida de Jean Valjean e outros personagens durante a Revolução Francesa e seus efeitos posteriores.'),
('O Conde de Monte Cristo', 'Um romance de Alexandre Dumas que narra a história de Edmond Dantès, um homem que busca vingança contra aqueles que o traíram.'),
('O Poder do Hábito', 'Um livro de Charles Duhigg que explora a ciência por trás dos hábitos e como eles podem ser mudados.'),
('A Sutil Arte de Ligar o F*da-se', 'Um livro de Mark Manson que explora como a felicidade pode ser alcançada por meio de uma vida com propósito.'),
('A Coragem de Ser Imperfeito', 'Um livro de Brené Brown que explora como a vulnerabilidade pode levar à coragem e à conexão.'),
('A Garota do Lago', 'Um romance de Charlie Donlea que segue a jornalista Kelsey Castle enquanto ela investiga um assassinato em uma cidade pequena.'),
('A Garota no Trem', 'Um romance de Paula Hawkins que segue Rachel Watson enquanto ela tenta descobrir o que aconteceu com uma mulher desaparecida.'),
('A Cor Púrpura', 'Um romance de Alice Walker que aborda temas de discriminação racial e sexual, narrado por meio de cartas e diários.'),
('O Conto de Aia', 'Um romance distópico de Margaret Atwood que descreve uma sociedade totalitária em que as mulheres são subjugadas.'),
('Crepúsculo', 'O primeiro livro da série de romance sobrenatural de Stephenie Meyer, que narra o romance entre uma adolescente e um vampiro.'),
('Lolita', 'Um polêmico romance de Vladimir Nabokov que narra a obsessão de um homem mais velho por uma jovem adolescente.'),
('A Mulher do Viajante no Tempo', 'Um romance de Audrey Niffenegger que explora o amor entre um homem cuja vida ocorre fora de ordem temporal e sua esposa.'),
('Laranja Mecânica', 'Um livro de Anthony Burgess que narra a história de Alex, um delinquente juvenil envolvido em atos de violência.'),
('Dom Quixote', 'Um clássico da literatura escrito por Miguel de Cervantes, que segue as aventuras do cavaleiro sonhador Dom Quixote e seu fiel escudeiro Sancho Pança.'),
('Divergente', 'O primeiro livro da trilogia de ficção científica de Veronica Roth, que se passa em uma sociedade dividida por facções.'),
('Convergente', 'O terceiro livro da trilogia "Divergente", que explora os desdobramentos finais da história.'),
('Insurgente', 'O segundo livro da trilogia "Divergente", que acompanha a protagonista em sua luta contra o sistema de facções.'),
('O Ladrão de Raios', 'O primeiro livro da série "Percy Jackson e os Olimpianos", que segue o jovem Percy Jackson enquanto ele descobre ser um semideus.'),
('O Mar de Monstros', 'O segundo livro da série "Percy Jackson e os Olimpianos", que acompanha Percy Jackson em sua busca pelo Velocino de Ouro.'),
('A Maldição do Titã', 'O terceiro livro da série "Percy Jackson e os Olimpianos", que segue Percy Jackson enquanto ele tenta salvar o mundo de um titã maligno.'),
('A Batalha do Labirinto', 'O quarto livro da série "Percy Jackson e os Olimpianos", que acompanha Percy Jackson em sua busca pelo labirinto de Dédalo.'),
('O Último Olimpiano', 'O quinto e último livro da série "Percy Jackson e os Olimpianos", que segue Percy Jackson em sua batalha final contra Cronos.'),
('Cidade dos Ossos', 'O primeiro livro da série "Os Instrumentos Mortais" de Cassandra Clare, que segue Clary Fray em um mundo de caçadores de sombras e criaturas sobrenaturais.'),
('As Vantagens de Ser Invisível', 'Um romance de Stephen Chbosky que narra as experiências de um adolescente chamado Charlie em seu primeiro ano de ensino médio.'),
('It: A Coisa', 'Um thriller de terror de Stephen King que descreve um grupo de amigos que enfrenta um ser maligno que assume a forma de seus piores medos.'),
('Carrie, A Estranha', 'O primeiro romance publicado de Stephen King, que conta a história de uma adolescente com poderes telecinéticos.'),
('Androides Sonham com Ovelhas Elétricas? (Blade Runner)', 'O romance de Philip K. Dick que inspirou o filme "Blade Runner", explorando questões de identidade e humanidade em um mundo distópico.'),
('Quem é Você, Alasca?', 'Um romance de John Green que segue o protagonista Miles Halter enquanto ele embarca em uma jornada para descobrir a verdadeira identidade de Alasca Young.'),
('Um Dobrar no Tempo', 'O primeiro livro da série de ficção científica de Madeleine L''Engle, que segue a jornada de Meg Murry em busca de seu pai desaparecido.'),
('Ponte para Terabítia', 'Um livro de Katherine Paterson que narra a amizade entre dois jovens, Jess e Leslie, e as aventuras que compartilham.'),
('Orgulho e Preconceito', 'O clássico romance de Jane Austen que explora temas de amor, casamento e preconceito na sociedade inglesa do século XIX.'),
('Maze Runner', 'O primeiro livro da série de ficção científica distópica de James Dashner, que segue um grupo de jovens presos em um labirinto.'),
('Os 13 Porquês', 'Um romance de Jay Asher que lida com temas de bullying, depressão e suicídio, narrado através de fitas deixadas pela protagonista.'),
('Cidades de Papel', 'Outro livro de John Green que segue a jornada de Quentin em busca de sua vizinha desaparecida, Margo.'),
('Wicked', 'Um romance de Gregory Maguire que reinventa a história da Bruxa Má do Oeste da Terra de Oz.'),
('A Seleção', 'O primeiro livro da série de Kiera Cass, que se passa em um futuro distópico onde garotas competem por uma chance de se casar com um príncipe.'),
('Pipi Meialonga', 'As travessuras da personagem Pipi Meialonga, criada por Astrid Lindgren, em uma série de histórias infantis.'),
('Belas Maldições', 'Um livro de Neil Gaiman e Terry Pratchett que narra a história de um anjo e um demônio que tentam evitar o fim do mundo.'),
('Sandman Edição Definitiva 1', 'O primeiro volume da série em quadrinhos "Sandman" de Neil Gaiman, que segue as aventuras do Senhor dos Sonhos.'),
('Sandman Edição Definitiva 2', 'O segundo volume da série "Sandman", que continua a saga do Senhor dos Sonhos.'),
('Sandman Edição Definitiva 3', 'O terceiro volume da série "Sandman", que explora ainda mais o mundo dos sonhos.'),
('Sandman Edição Definitiva 4', 'O quarto volume da série "Sandman", que continua a cativante história do Senhor dos Sonhos.'),
('Sandman Edição Definitiva 5', 'O quinto e último volume da série "Sandman", concluindo a épica jornada do Senhor dos Sonhos.'),
('Guerra Civil', 'Uma série de quadrinhos da Marvel Comics que narra o conflito entre super-heróis e o governo dos Estados Unidos.'),
('Injustiça: Deuses Entre Nós', 'Uma série de quadrinhos baseada no universo de DC Comics que explora um mundo onde Superman se torna um ditador após uma tragédia.');